import { getDateWithOffset } from './utilities'

export const tasks = [
  {
    id: 1,
    type: 'שיחה',
    description: 'להתקשר ללקוחות שהשאירו פרטים',
    dateTime: getDateWithOffset(-1),
    displayTime: false,
    assignedUser: 'אני',
    customer: 'שירי מזור',
    product: 'סימפלאן מערכת מלאה - מנוי חודשי',
    comment: 'הערה חשובה מאוד',
  },
  {
    id: 2,
    type: 'כללי',
    description: 'לכתוב תסריט לארבעה סרטונים חדשים',
    dateTime: getDateWithOffset(0, 23, 59, 59, 999),
    displayTime: false,
    assignedUser: 'אוראל ספיר',
    customer: null,
    product: 'מוצרי עבר CEO',
    comment: 'לשאול רשימת שאלות',
  },
  {
    id: 3,
    type: 'פיננסי',
    description: 'להעביר את התשלום לצוות הפיתוח',
    dateTime: getDateWithOffset(0, 8, 0),
    displayTime: true,
    assignedUser: 'אני',
    customer: 'הדר כץ',
    product: null,
    comment: null,
  },
  {
    id: 4,
    type: 'פגישה',
    description: 'לקבוע פגישה עם אוראל ספיר',
    dateTime: getDateWithOffset(0, 20, 0),
    displayTime: true,
    assignedUser: 'אני',
    customer: 'ירדן סמואלוב',
    product: null,
    comment: 'לא לשכוח לקחת מסמכים',
  },
  {
    id: 5,
    type: 'כללי',
    description: 'לכתוב את הבריף לפגישה של יום חמישי',
    dateTime: null,
    displayTime: false,
    assignedUser: 'עמרי ברגמן',
    customer: null,
    product: 'מוצרי עבר CEO',
    comment: 'הערה חשובה מאוד',
  },
  {
    id: 6,
    type: 'פיננסי',
    description: 'להעביר את הדו"חות לרואה חשבון',
    dateTime: getDateWithOffset(1, 16, 0),
    displayTime: true,
    assignedUser: 'אביב כהן',
    customer: 'יהודית וייס',
    product: 'סימפלאן מערכת מלאה - מנוי חודשי',
    comment: null,
  },
  {
    id: 7,
    type: 'כללי',
    description: 'לחפש ספקים למוצר החדש',
    dateTime: getDateWithOffset(2, 8, 0),
    displayTime: true,
    assignedUser: 'אני',
    customer: null,
    product: null,
    comment: 'הערה חשובה מאוד',
  },
  {
    id: 8,
    type: 'פגישה',
    description: 'פגישה עם המנכ"ל',
    dateTime: getDateWithOffset(7, 10, 0),
    displayTime: true,
    assignedUser: 'אני',
    customer: null,
    product: null,
    comment: 'הערה חשובה מאוד',
  },
]
